### PR TITLE
Class load issue

### LINKED ISSUE #212: Could not find or load main class
**Describe the bug**
Got below error in adamaJava 36-ef3dc161
```
$java -jar q3tiledaligner.jar -h
Error: Could not find or load main class au.edu.qimr.tiledaligner.Q3TiledAligner
...
$java -jar q3vcftools.jar -h
Error: Could not find or load main class au.edu.qimr.vcftools.Merge
...
```

**Expected behavior**
the build file should update since the main class name changed:
1.  from Q3TiledAligner to TiledAligner  in q3tiledaligner/build.gradle:  
`mainClassName = 'au.edu.qimr.tiledaligner.TiledAligner'`
2. from Merge to MergeSameSamples in q3vcftools/build.gradle:   
`mainClassName = 'au.edu.qimr.vcftools.MergeSameSamples'`
 
**Desktop (please complete the following information):**
 - OS: linux or Mac
 - Version : 3.10.0-693.11.6.el7.x86_64 or mac10.14.6

### PR DESCRIPTION
**Pull request by ChristinaXu2017**
# Description

There are java classes loading issue in q3panel, q3vcftools, and q3tiledaligner. The reasons are described in issue 212 and 213.  Here we move SmithWatermanGotoh.java from qmule to qcommon, hence both q3panel and q3tiledaligner can get rid of qmule. 

In this pull request, we also change org.testng.annotations.Test to org.junit.Test. The reason is both Test are very similar and do the same thing  in PositionChrPositionMapTest.java.  Here org.testng is  imported by qpicard, but qpicard is also imported by qmule.   After t3tiledaligner get rid of qmule package, it is better to switch back to junit.test. 

Fixes #212 #213 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [X] Test A: existing unit test
- [X] Test B: creating regression test to run qtiledaligner, and then q3panel and q3vcftools

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java [hunk 1]
```diff
@@ -4,7 +4,7 @@
  *
  * This code is released under the terms outlined in the included LICENSE file.
  */
-package org.qcmg.qmule;
+package org.qcmg.common.model;
```
Comment (holmeso) [inline qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java:7]: consider a different location within qcommon, model is meant for POJOs

**Review by holmeso — CHANGES_REQUESTED** [review]

File: qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java (hunk 1 above)
Comment (ChristinaXu2017) [reply qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java:7]: really not sure where to fit it in. How about org.qcmg.common.utils? alternatively, we can modify SmithWatermanGotoh.java to make it to be POJO class.  I also guess this class is still in development, it may move again. 
anyway, it is up to your suggestion since you are the owner of it.

Comment (holmeso) [reply qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java:7]: how about putting it into its own package? `sw` sounds good

Comment (ChristinaXu2017) [reply qcommon/src/org/qcmg/common/model/SmithWatermanGotoh.java]: yes, all good now!

**Review by holmeso — APPROVED** [review]
looks good
